<?php

/**
 * @file List of modules to enable.
 */
$enable = array(
  // Core.
  'color',
  'dblog',
  'menu',
  'taxonomy',
  // Contrib.
  'admin_menu',
  'admin_menu_toolbar',
  'admin_views',
  'ctools',
  'ctools_custom_content',
  'date',
  'entity',
  'entityreference',
  'features',
  'file_entity',
  'inline_entity_form',
  'redirect',
  'panels',
  'ldap',
  'libraries',
  'link',
  'media',
  'oauth',
  'page_manager',
  'panels_everywhere',
  'pathauto',
  'secure_permissions',
  'strongarm',
  'token',
  'uuid',
  'views',
  'views_content',
  'ckeditor',
  // Custom.
  'cex_sharedentities',
  'corp_preview',
);
