<?php

/**
 * @file List of modules to disable.
 */
$disable = array(
  'ds',
//    'aggregator',
//    'blog',
//    'book',
//    'color',
//    'comment',
//    'contact',
//    'translation',
//    'dashboard',
//    'forum',
//    'locale',
//    'openid',
//    'overlay',
//    'php',
//    'poll',
//    'shortcut',
//    'statistics',
//    'syslog',
//    'toolbar',
//    'tracker',
//    'trigger',
//    'profile',
//    'tracker',
//    'trigger',
//    'magic',
);
